name: fingerprint_with_qr_scan_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  device_info_plus: ^11.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  local_auth: ^2.3.0
  mobile_scanner: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
